const mongoose=require("mongoose")


const foodSchema= new mongoose.Schema({
    title:{type:String,required:[true,"Food title is required"]},
    description:{type:String,default:""},
    price:{type:Number,required:[true,"Food price is required"]},
    imgUrl:{type:String,default:""},
    categoryId:{type:mongoose.Schema.Types.ObjectId,ref:"Category"},
    restaurantId:{type:mongoose.Schema.Types.ObjectId,ref:"Restaurant"},
    isAvailable:{type:Boolean,default:true},
    rating:{type:Number,default:1,max:5,min:1},
    ratingCount:{type:Number,default:0},
    ingredients:{type:Array,default:[]},
    isPopular:{type:Boolean,default:false},
    isRecommended:{type:Boolean,default:false},
    isVeg:{type:Boolean,default:false},
    isNonVeg:{type:Boolean,default:false},
    isSpicy:{type:Boolean,default:false},
    isDiscount:{type:Boolean,default:false},
    discount:{type:Number,default:0},
    discountType:{type:String,default:""},
    discountDescription:{type:String,default:""},
    isTodaySpecial:{type:Boolean,default:false},
    isFastDelivery:{type:Boolean,default:false},
    isFreeDelivery:{type:Boolean,default:false},
    isTopRated:{type:Boolean,default:false},
    isPopular:{type:Boolean,default:false},
    isRecommended:{type:Boolean,default:false},
    isDiscount:{type:Boolean,default:false},
    isAvailable:{type:Boolean,default:true},
    isTodaySpecial:{type:Boolean,default:false},
    isFastDelivery:{type:Boolean,default:false},
    isFreeDelivery:{type:Boolean,default:false},
    isTopRated:{type:Boolean,default:false},
    isPopular:{type:Boolean,default:false},
    isRecommended:{type:Boolean,default:false},
    isDiscount:{type:Boolean,default:false},
    isAvailable:{type:Boolean,default:true},
    isTodaySpecial:{type:Boolean,default:false},
    isFastDelivery:{type:Boolean,default:false},
    isFreeDelivery:{type:Boolean,default:false},
    isTopRated:{type:Boolean,default:false},
    isPopular:{type:Boolean,default:false},
    isRecommended:{type:Boolean,default:false},
    isDiscount:{type:Boolean,default:false},
    isAvailable:{type:Boolean,default:true},
    isTodaySpecial:{type:Boolean,default:false},
    isFastDelivery:{type:Boolean,default:false},
    isFreeDelivery:{type:Boolean,default:false},
    isTopRated:{type:Boolean,default:false},
    isPopular:{type:Boolean,default:false},
    isRecommended:{type:Boolean,default:false},
    isDiscount:{type:Boolean,default:false},
})


module.exports=mongoose.model("Food",foodSchema)